server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiples-instancias
          uri: https://github.com/oxrl/eureka-server
          search-paths: config-data
  application:
    name: config-service
